# Generated by Django 4.2 on 2023-07-20 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provider',
            old_name='clinic_name',
            new_name='works_for_clinic',
        ),
    ]
