# Generated by Django 4.2 on 2023-07-15 10:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('website_name', models.CharField(blank=True, max_length=50, null=True)),
                ('website_url', models.URLField(blank=True, max_length=100, null=True)),
                ('admin_website', models.CharField(blank=True, max_length=100, null=True)),
                ('user_website', models.CharField(blank=True, max_length=100, null=True)),
                ('admin_pass', models.CharField(blank=True, max_length=100, null=True)),
                ('user_pass', models.CharField(blank=True, max_length=100, null=True)),
                ('email_website', models.EmailField(blank=True, max_length=100, null=True)),
                ('email_pass', models.EmailField(blank=True, max_length=100, null=True)),
                ('domain_website', models.CharField(choices=[('Dynadot', 'Dynadot'), ('GoDaddy', 'GoDaddy'), ('IONOS', 'IONOS')], default='Dynadot', max_length=20)),
                ('hosted_website', models.CharField(choices=[('DigitalOcean', 'DigitalOcean'), ('Hostinger', 'Hostinger'), ('Bluehost', 'Bluehost')], default='DigitalOcean', max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
