# Generated by Django 4.2 on 2023-07-15 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='email_pass',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
