# Generated by Django 4.2 on 2023-07-15 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0002_alter_website_email_pass'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainProviders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HostingProviders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publishing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publishing_frequency', models.CharField(blank=True, max_length=20, null=True)),
                ('publishing_day', models.CharField(blank=True, max_length=20, null=True)),
                ('publishing_per', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='website',
            name='domain_website',
        ),
        migrations.RemoveField(
            model_name='website',
            name='hosted_website',
        ),
        migrations.AddField(
            model_name='website',
            name='publishing_frequency',
            field=models.CharField(choices=[('OnceDaily', 'OnceDaily'), ('4/Week', '4/Week')], default='OnceDaily', max_length=20),
        ),
        migrations.AddField(
            model_name='website',
            name='publishing_status',
            field=models.CharField(choices=[('Live', 'Live'), ('Publishing', 'Publishing')], default='Live', max_length=20),
        ),
        migrations.AddField(
            model_name='website',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('InActive', 'InActive')], default='Active', max_length=10),
        ),
        migrations.AddField(
            model_name='website',
            name='domain_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='website_app.domainproviders'),
        ),
        migrations.AddField(
            model_name='website',
            name='hosting_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='website_app.hostingproviders'),
        ),
    ]
