# Generated by Django 4.2 on 2023-07-15 16:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0003_domainproviders_hostingproviders_publishing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='website',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
