# Generated by Django 4.2 on 2023-07-20 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0006_website_website_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='website_business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='website_app.websitebusinessmodel'),
        ),
    ]
