# Generated by Django 4.2 on 2023-07-20 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0007_alter_website_website_business'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='website_business',
        ),
    ]
