# Generated by Django 4.2 on 2023-07-22 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0008_remove_website_website_business'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='is_deleted',
        ),
    ]
