# Generated by Django 4.2 on 2023-07-22 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0010_remove_website_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Publishing',
        ),
        migrations.RemoveField(
            model_name='websitebusinessmodel',
            name='business_company',
        ),
        migrations.RemoveField(
            model_name='websitebusinesstype',
            name='model_type',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='WebsiteBusinessModel',
        ),
        migrations.DeleteModel(
            name='WebsiteBusinesstype',
        ),
    ]
