# Generated by Django 4.2 on 2023-07-27 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0011_delete_publishing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='server',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
