# Generated by Django 4.2 on 2023-07-28 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0012_website_server'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonAssociates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amazon_associates_email', models.EmailField(max_length=100, null=True)),
                ('amazon_tag', models.CharField(max_length=150, null=True)),
                ('amazon_location', models.CharField(choices=[('USA', 'Amazon USA'), ('IND', 'Amazon India')], default='USA', max_length=5)),
            ],
        ),
    ]
