# Generated by Django 4.2 on 2023-07-28 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0013_amazonassociates'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='amazon_associates_tag',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='associate_tag', to='website_app.amazonassociates'),
        ),
        migrations.AddField(
            model_name='website',
            name='amazon_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='associate_email', to='website_app.amazonassociates'),
        ),
    ]
