# Generated by Django 4.2 on 2023-07-25 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('writers_app', '0002_writer_article_alloted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writer',
            name='article_alloted',
        ),
    ]
