# Generated by Django 4.2 on 2023-07-20 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('website_app', '0005_company_websitebusinessmodel_alter_website_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Youtube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(blank=True, max_length=100, null=True)),
                ('website_associated', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website_app.website')),
            ],
        ),
    ]
