# Generated by Django 4.2 on 2023-07-29 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yt_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeIdeas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_idea', models.CharField(blank=True, max_length=200, null=True)),
                ('ideas_keywords', models.TextField(blank=True, max_length=1000, null=True)),
                ('idea_expansion', models.TextField(blank=True, max_length=1000, null=True)),
                ('video_creation_status', models.CharField(choices=[('IDEAONLY', 'Idea Stage'), ('SCRIPTED', 'Script Completed'), ('FILMED', 'Filming Completed'), ('EDITED', 'Edit Completed'), ('UPLOADREADY', 'Upload Ready')], default='IDEAONLY', max_length=15)),
                ('video_channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='yt_app.youtube')),
            ],
        ),
    ]
