# Generated by Django 4.2 on 2023-07-21 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0002_alter_city_state_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='city_name',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='state_name',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='country_name',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='country_name',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='state_name',
            new_name='state',
        ),
    ]
