# Generated by Django 4.2 on 2023-08-06 17:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskTracker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('publishing_status', models.CharField(choices=[('Live', 'Live'), ('Publishing', 'Publishing')], default='Live', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('task_name', models.CharField(blank=True, max_length=150, null=True)),
                ('task_description', models.TextField(blank=True, max_length=5000, null=True)),
                ('assigned_by', models.CharField(choices=[('LOU', 'Louise'), ('FAZ', 'Fayez'), ('WIL', 'William')], default='LOUISE', max_length=3)),
                ('status', models.CharField(choices=[('INP', 'inProgress'), ('REG', 'Regular'), ('COM', 'Completed')], default='INPROGRESS', max_length=3)),
                ('scope', models.CharField(choices=[('NP', 'Excluded'), ('REG', 'Added'), ('COM', 'Driven')], default='WAITING', max_length=3)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
