# Generated by Django 4.2 on 2023-07-22 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='article_status',
            field=models.CharField(choices=[('WRT', 'Writing'), ('WAT', 'Waiting'), ('PED', 'Pending'), ('COM', 'Completed'), ('PUB', 'Published')], default='WAITING', max_length=3),
        ),
        migrations.AddField(
            model_name='article',
            name='main_keyword',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='sub_keywords',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
